[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qpatlib"
version = "0.1.0"
description = "QPatLib: tooling for generating circuits and MBQC patterns (patterns are published separately on Zenodo)."
readme = "README.md"
requires-python = "=3.11"
license = {text = "MIT"}
authors = [
  {name = "Vito Scarola"}
]
keywords = [
  "MBQC", "measurement-based quantum computing", "measurement calculus",
  "graph states", "Graphix", "OpenQASM 3"
]
dependencies = [
  "numpy>=1.23",
  "networkx>=3.0",
  "requests>=2.31",
  "qiskit>=1.0",
  "graphix =0.3.3",
  "openqasm3>=1.0.0",
  "jupyterlab>=4.0",
  "ipykernel>=6.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0",
  "ruff>=0.4",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
